config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/DetectorSim-3DGAN:
      branch: main
      repo: https://github.com/interTwin-eu/DetectorSim-3DGAN
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/DetectorSim-3DGAN git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-yellow-caracal.sh
        container: qc.acc_goopy-fuchsia-falcon
  QC.Doc:
    repos:
      github.com/interTwin-eu/DetectorSim-3DGAN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-rose-mole.sh
        container: qc.doc_baggy-brass-sparrow
      github.com/interTwin-eu/DetectorSim-3DGAN git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-scarlet-binturong.sh
        container: qc.doc_clammy-saffron-numbat
  QC.Lic:
    repos:
      github.com/interTwin-eu/DetectorSim-3DGAN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-dandelion-hyrax.sh
        container: qc.lic_tacky-cardinal-frigatebird
  QC.Ver:
    repos:
      github.com/interTwin-eu/DetectorSim-3DGAN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-beige-balinese.sh
        container: qc.ver_freaky-lemon-spitz
timeout: 5400
